#log-file="~~desktop/mpv.log"            # 输出log在桌面
 keep-open=yes                           # 播放完毕后不自动退出
 save-position-on-quit=yes               # 退出时保存当前播放状态
 audio-file-auto=fuzzy                   # 自动加载同名外置音轨
#icc-profile-auto                        # 进行校色
 icc-cache-dir="/tmp/icc_cache"            # 保存缓存加速启动
#profile=gpu-hq                          # 使用内置的预设的较高画质方案
 gpu-shader-cache-dir="/tmp/shaders_cache" # 保存缓存加速启动
 sub-auto=fuzzy                          # 自动加载同名外置字幕
 screenshot-directory="~/Desktop/"       # 截图输出在桌面
